<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Model;

use Redirection\Model\Base\PermanentRedirectionI18n as BasePermanentRedirectionI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class PermanentRedirectionI18n
 * @package Redirection\Model
 */
class PermanentRedirectionI18n extends BasePermanentRedirectionI18n
{
    use I18nTimestampableTrait;
}
