<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Action;

use Redirection\Action\Base\PermanentRedirectionAction as  BasePermanentRedirectionAction;

/**
 * Class PermanentRedirectionAction
 * @package Redirection\Action
 */
class PermanentRedirectionAction extends BasePermanentRedirectionAction
{
}
