<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Form\Type;

use Redirection\Form\Type\Base\PermanentRedirectionIdType as BasePermanentRedirectionIdType;

/**
 * Class PermanentRedirection
 * @package Redirection\Form
 */
class PermanentRedirectionIdType extends BasePermanentRedirectionIdType
{
}
