<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Event;

use Redirection\Event\Base\PermanentRedirectionEvent as BasePermanentRedirectionEvent;

/**
 * Class PermanentRedirectionEvent
 * @package Redirection\Event
 */
class PermanentRedirectionEvent extends BasePermanentRedirectionEvent
{
}
