<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Event;

use Redirection\Event\Base\PermanentRedirectionEvents as BasePermanentRedirectionEvents;

/**
 * Class PermanentRedirectionEvents
 * @package Redirection\Event
 */
class PermanentRedirectionEvents extends BasePermanentRedirectionEvents
{
}
