<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Form\Base;

use Redirection\Form\PermanentRedirectionCreateForm as ChildPermanentRedirectionCreateForm;
use Redirection\Form\Type\PermanentRedirectionIdType;

/**
 * Class PermanentRedirectionForm
 * @package Redirection\Form
 * @author TheliaStudio
 */
class PermanentRedirectionUpdateForm extends ChildPermanentRedirectionCreateForm
{
    const FORM_NAME = "permanent_redirection_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", PermanentRedirectionIdType::TYPE_NAME)
            ->remove("visible")
        ;
    }
}
