<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Form\Base;

use Redirection\Redirection;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class PermanentRedirectionCreateForm
 * @package Redirection\Form\Base
 * @author TheliaStudio
 */
class PermanentRedirectionCreateForm extends BaseForm
{
    const FORM_NAME = "permanent_redirection_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addVisibleField($translationKeys, $fieldsIdKeys);
        $this->addPathField($translationKeys, $fieldsIdKeys);
        $this->addDestinationField($translationKeys, $fieldsIdKeys);
        $this->addTitleField($translationKeys, $fieldsIdKeys);
        $this->addChapoField($translationKeys, $fieldsIdKeys);
        $this->addLocaleField();
    }

    public function addLocaleField()
    {
        $this->formBuilder->add(
            'locale',
            'hidden',
            [
                'constraints' => [ new NotBlank() ],
                'required'    => true,
            ]
        );
    }

    protected function addVisibleField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("visible", "checkbox", array(
            "label" => $this->translator->trans($this->readKey("visible", $translationKeys), [], Redirection::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("visible", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addPathField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("path", "textarea", array(
            "label" => $this->translator->trans($this->readKey("path", $translationKeys), [], Redirection::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("path", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addDestinationField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("destination", "textarea", array(
            "label" => $this->translator->trans($this->readKey("destination", $translationKeys), [], Redirection::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("destination", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addTitleField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("title", "text", array(
            "label" => $this->translator->trans($this->readKey("title", $translationKeys), [], Redirection::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("title", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addChapoField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("chapo", "textarea", array(
            "label" => $this->translator->trans($this->readKey("chapo", $translationKeys), [], Redirection::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("chapo", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "visible" => "permanent_redirection_visible",
            "position" => "permanent_redirection_position",
            "path" => "permanent_redirection_path",
            "destination" => "permanent_redirection_destination",
            "title" => "permanent_redirection_title",
            "chapo" => "permanent_redirection_chapo",
        );
    }
}
