<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Loop;

use Redirection\Loop\Base\PermanentRedirection as BasePermanentRedirectionLoop;

/**
 * Class PermanentRedirection
 * @package Redirection\Loop
 */
class PermanentRedirection extends BasePermanentRedirectionLoop
{
    /**
     * You may now add your own logic
     */
}
