<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Form;

use Redirection\Form\Base\PermanentRedirectionUpdateForm as BasePermanentRedirectionUpdateForm;

/**
 * Class PermanentRedirectionUpdateForm
 * @package Redirection\Form
 */
class PermanentRedirectionUpdateForm extends BasePermanentRedirectionUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "position" => "position",
            "path" => "Path",
            "destination" => "Destination",
            "title" => "Title",
            "chapo" => "Chapo",
        );
    }
}
