<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use Redirection\Event\PermanentRedirectionEvent;
use Redirection\Event\PermanentRedirectionEvents;
use Redirection\Model\PermanentRedirectionQuery;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;

/**
 * Class PermanentRedirectionController
 * @package Redirection\Controller\Base
 * @author TheliaStudio
 */
class PermanentRedirectionController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "permanent_redirection",
            "manual",
            "order",
            AdminResources::MODULE,
            PermanentRedirectionEvents::CREATE,
            PermanentRedirectionEvents::UPDATE,
            PermanentRedirectionEvents::DELETE,
            PermanentRedirectionEvents::TOGGLE_VISIBILITY,
            PermanentRedirectionEvents::UPDATE_POSITION,
            "Redirection"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("permanent_redirection.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("permanent_redirection.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "visible" => (bool) $object->getVisible(),
            "position" => $object->getPosition(),
            "path" => $object->getPath(),
            "destination" => $object->getDestination(),
            "title" => $object->getTitle(),
            "chapo" => $object->getChapo(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new PermanentRedirectionEvent();

        $event->setVisible($formData["visible"]);
        $event->setPath($formData["path"]);
        $event->setDestination($formData["destination"]);
        $event->setTitle($formData["title"]);
        $event->setChapo($formData["chapo"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new PermanentRedirectionEvent();

        $event->setId($formData["id"]);
        $event->setVisible($formData["visible"]);
        $event->setPath($formData["path"]);
        $event->setDestination($formData["destination"]);
        $event->setTitle($formData["title"]);
        $event->setChapo($formData["chapo"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new PermanentRedirectionEvent();

        $event->setId($this->getRequest()->request->get("permanent_redirection_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getPermanentRedirection();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return PermanentRedirectionQuery::create()
            ->findPk($this->getRequest()->query->get("permanent_redirection_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return $object->getTitle();
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("permanent-redirections");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "permanent_redirection_id",
                $this->getRequest()->query->get("permanent_redirection_id")
            )
        ;

        return $this->render("permanent-redirection-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("permanent_redirection_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/Redirection/permanent_redirection/edit",
                [
                    "permanent_redirection_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/Redirection/permanent_redirection")
        );
    }

    protected function createToggleVisibilityEvent()
    {
        return new ToggleVisibilityEvent($this->getRequest()->query->get("permanent_redirection_id"));
    }
    
    protected function createUpdatePositionEvent($positionChangeMode, $positionValue)
    {
        return new UpdatePositionEvent(
            $this->getRequest()->query->get("permanent_redirection_id"),
            $positionChangeMode,
            $positionValue
        );
    }
}
