<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Event\Base;

/**
 * Class PermanentRedirectionEvents
 * @package Redirection\Event\Base
 * @author TheliaStudio
 */
class PermanentRedirectionEvents
{
    const CREATE = "action.permanent_redirection.create";
    const UPDATE = "action.permanent_redirection.update";
    const DELETE = "action.permanent_redirection.delete";
    const UPDATE_POSITION = "action.permanent_redirection.update_position";
    const TOGGLE_VISIBILITY = "action.permanent_redirection.toggle_visilibity";
}
