<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Controller;

use Redirection\Controller\Base\PermanentRedirectionController as BasePermanentRedirectionController;

/**
 * Class PermanentRedirectionController
 * @package Redirection\Controller
 */
class PermanentRedirectionController extends BasePermanentRedirectionController
{
}
