<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Redirection\Action\Base;

use Redirection\Model\Map\PermanentRedirectionTableMap;
use Redirection\Event\PermanentRedirectionEvent;
use Redirection\Event\PermanentRedirectionEvents;
use Redirection\Model\PermanentRedirectionQuery;
use Redirection\Model\PermanentRedirection;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class PermanentRedirectionAction
 * @package Redirection\Action
 * @author TheliaStudio
 */
class PermanentRedirectionAction extends BaseAction implements EventSubscriberInterface
{
    public function create(PermanentRedirectionEvent $event)
    {
        $this->createOrUpdate($event, new PermanentRedirection());
    }

    public function update(PermanentRedirectionEvent $event)
    {
        $model = $this->getPermanentRedirection($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(PermanentRedirectionEvent $event)
    {
        $this->getPermanentRedirection($event)->delete();
    }

    protected function createOrUpdate(PermanentRedirectionEvent $event, PermanentRedirection $model)
    {
        $con = Propel::getConnection(PermanentRedirectionTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            $model->setLocale($event->getLocale());

            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $visible = $event->getVisible()) {
                $model->setVisible($visible);
            }

            if (null !== $position = $event->getPosition()) {
                $model->setPosition($position);
            }

            if (null !== $path = $event->getPath()) {
                $model->setPath($path);
            }

            if (null !== $destination = $event->getDestination()) {
                $model->setDestination($destination);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $chapo = $event->getChapo()) {
                $model->setChapo($chapo);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setPermanentRedirection($model);
    }

    protected function getPermanentRedirection(PermanentRedirectionEvent $event)
    {
        $model = PermanentRedirectionQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'permanent_redirection' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function updatePosition(UpdatePositionEvent $event)
    {
        $this->genericUpdatePosition(new PermanentRedirectionQuery(), $event);
    }

    public function toggleVisibility(ToggleVisibilityEvent $event)
    {
        $this->genericToggleVisibility(new PermanentRedirectionQuery(), $event);
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            PermanentRedirectionEvents::CREATE => array("create", 128),
            PermanentRedirectionEvents::UPDATE => array("update", 128),
            PermanentRedirectionEvents::DELETE => array("delete", 128),
            PermanentRedirectionEvents::UPDATE_POSITION => array("updatePosition", 128),
            PermanentRedirectionEvents::TOGGLE_VISIBILITY => array("toggleVisibility", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".permanent_redirection_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".permanent_redirection_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".permanent_redirection_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".permanent_redirection_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
